version: "3"

services:
  backend:
    build:
      context: ./smartcontract-analyzer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000
    volumes:
      - ./smartcontract-analyzer:/usr/src/app
      - backend-modules:/usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/frontend:/usr/src/app
      - frontend-modules:/usr/src/app/node_modules

volumes:
  backend-modules:
  frontend-modules:
