version: "3"

services:
  backend:
    build:
      context: ./smartcontract-analyzer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000
    volumes:
      - ./smartcontract-analyzer:/usr/src/app
      - backend-modules:/usr/src/app/node_modules

  frontend:
    build:
      context: ./BlockHack-Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - ./BlockHack-Frontend:/usr/src/app
      - frontend-modules:/usr/src/app/node_modules

volumes:
  backend-modules:
  frontend-modules:
